### ISSUE TITLE
로컬 테스트 환경 셋업

### ISSUE THREAD

**Issue by homekeeper89** [Taehoya/bside-4#10]
- docker 등 기본 인프라 환경 세팅
- jest 등 test 셋업

**Comment by Taehoya** [comment]
nest project를 initialize 하면서 기본적인 Jest 설정이 되어있는거 같은데 혹시 test셋업에 대해서 어디까지 생각하시나요?

**Comment by homekeeper89** [comment]
> nest project를 initialize 하면서 기본적인 Jest 설정이 되어있는거 같은데 혹시 test셋업에 대해서 어디까지 생각하시나요?

실제 테스트 위한 app setup 등을 뜻합니다. context 설정 및 mock 등

**Comment by homekeeper89** [comment]
> nest project를 initialize 하면서 기본적인 Jest 설정이 되어있는거 같은데 혹시 test셋업에 대해서 어디까지 생각하시나요?

아 이거 e2e test 까지는 셋업 되어있군요, service 등 테스트 환경 구성까지 생각하면 될것 같긴 하네요
